/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomLayout: typeof import('./components/CustomLayout.vue')['default']
    FunctionGraph: typeof import('./components/FunctionGraph.vue')['default']
    NavAuth: typeof import('./components/NavAuth.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
  }
}
